### PR TITLE
test: add SonarCloud

### PR DESCRIPTION
**Pull request by DanielRuf**
**Type:**
test / CI

The following has been addressed in the PR:

*  prepare SonarCloud

**Description:**

This adds the required minimal configuration to enable SonarCloud scans.

### CODE REVIEW

**Comment by juanpicado** [comment]
@DanielRuf app approved

**Comment by DanielRuf** [comment]
Awesome. Now you just have to create the org and project at sonarcloud.io through https://github.com/apps/sonarcloud/installations/new for `verdaccio/ui`.

**Comment by sergiohgz** [comment]
We need to configure to execute on a CI, in this case, I think CircleCI should be the target.

**Comment by DanielRuf** [comment]
> We need to configure to execute on a CI, in this case, I think CircleCI should be the target.

We don't have to, it will be automatically added as extra check when it is completely setup and configured.

No need to change CI setup.

**Comment by DanielRuf** [comment]
At least it should be only for PRs as extra check (code quality, code smells, ...).

**Comment by juanpicado** [comment]
I will do some test

**Pull request merged**
