### PR TITLE
feat(lang): Add turkish language

### PR DESCRIPTION
**Pull request by tugsanunlu**
**Type:** Translation

**Description:** I added Turkish translation requirements for Verdaccio Web User Interface.

### CODE REVIEW

**Comment by tugsanunlu** [comment]
There are errors in CI. Are these related to my code?

**Comment by DanielRuf** [comment]
Probably not related to your changes. I will trigger a new CI build.

**Comment by DanielRuf** [comment]
Not sure if this is related to the language addition. Could be possible.

Bildschirmfoto 2020-08-28 um 13 23 00

**Comment by DanielRuf** [comment]
Please use a separate branch in your fork in the future =)

Bildschirmfoto 2020-08-28 um 13 24 49

**Comment by DanielRuf** [comment]
Please use a separate branch in your fork in the future (some rbanch like àdd-turkish-language`) =)
Because if we push something to our master branch there could be conflicts and this is an anti-pattern.


Bildschirmfoto 2020-08-28 um 13 24 49

**Comment by DanielRuf** [comment]
@juanpicado do you know why this happens? Is this related to the branch name? The errors are not that helpful.

Bildschirmfoto 2020-08-28 um 13 27 05

**Comment by tugsanunlu** [comment]
> Please use a separate branch in your fork in the future (some rbanch like àdd-turkish-language`) =)
> Because if we push something to our master branch there could be conflicts and this is an anti-pattern.
> 
> Bildschirmfoto 2020-08-28 um 13 24 49

I'll pay attention next time. Thanks.

**Comment by juanpicado** [comment]
> @juanpicado do you know why this happens? Is this related to the branch name? The errors are not that helpful.
> 
> Bildschirmfoto 2020-08-28 um 13 27 05

fails because forks cannot access to secrets as far I know.

**Review by juanpicado — APPROVED** [review]
Great job @tugsanunlu  !!! It will be available in the next release

**Comment by juanpicado** [comment]
> Please use a separate branch in your fork in the future (some rbanch like àdd-turkish-language`) =)
> Because if we push something to our master branch there could be conflicts and this is an anti-pattern.
> 
> Bildschirmfoto 2020-08-28 um 13 24 49

Good advice 👏

**Comment by DanielRuf** [comment]
@juanpicado

> fails because forks cannot access to secrets as far I know.

Ah ok, that makes sense. This is one of our own actions? Maybe we should provide a better error / warning.

**Comment by juanpicado** [comment]
> @juanpicado
> 
> > fails because forks cannot access to secrets as far I know.
> 
> Ah ok, that makes sense. This is one of our own actions? Maybe we should provide a better error / warning.

Yes, I think GitHub still does not allows that. What we might do is just filter by branch name and only include local branches.

**Pull request merged**
