### PR TITLE
Fix: removed unused style file

### LINKED ISSUE #95: Investigate how to remove !important in styles
`!important` CSS keyword carries several behaviours in accessibility, so we have to try avoid their usage as much as we can.

We could try to make important things by repeating CSS class name instead, as commented in the PR referenced below.

_Originally posted by @sergiohgz in https://github.com/verdaccio/ui/pull/85_

### PR DESCRIPTION
**Pull request by priscilawebdev**
**Type:** Bug

**Description:**

Fixes #95

### CODE REVIEW

**Comment by sergiohgz** [comment]
Did you add invalid for a reason?

**Comment by priscilawebdev** [comment]
@sergiohgz yes... the code I removed doesn't seems right..hmm but actually it is a solution...I will remove the tag :)

**Comment by sergiohgz** [comment]
If it doesn't seems right, does it really apply?

**Comment by priscilawebdev** [comment]
sorry...I confused you..my PR solves the problem 😉

**Comment by sergiohgz** [comment]
Aaaa, perfect 👌

**Pull request merged**
