### PR TITLE
fix: remove whitespace from logo image - closes #374

### LINKED ISSUE #374: Header icon is displaced in header
**Describe the bug**

The icon is displaced and not centered anymore.

Kapture 2019-12-16 at 21 20 16

**To Reproduce**

Just compare local master 

`http://localhost:4872/-/web/detail/jquery`
vs
`https://registry.verdaccio.org/-/web/detail/jquery`

**Expected behavior**

Icon should be center and match with the `v4.3.4`

### PR DESCRIPTION
**Pull request by DanielRuf**
**Type:**
bugfix

The following has been addressed in the PR:

*  Remove whitespace from image using `font-size: 0`.

See also https://css-tricks.com/fighting-the-space-between-inline-block-elements/

**Description:**

Resolves #374

### CODE REVIEW

**Comment by juanpicado** [comment]
Again snapshots :( are failing ...

**Comment by DanielRuf** [comment]
Some bot token issue: https://github.com/verdaccio/ui/pull/400/checks?check_run_id=363440405

**Comment by DanielRuf** [comment]
Failing snapshots, one test would need snapshot updates every year: https://circleci.com/gh/verdaccio/ui/6584?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

We should improve this.

**Comment by juanpicado** [comment]
There is something planned https://github.com/verdaccio/ui/issues/199

**Comment by juanpicado** [comment]
@DanielRuf could you update snapshots?

**Comment by DanielRuf** [comment]
Which exact command is needed for that and is that currently documented?

**Comment by juanpicado** [comment]
At `jest` you need to add an argument `-u`. Perhaps worth to add a new script

`"test:snapshopts": "npm run test -- -u",`

to facilitate this process while the other ticket is being fixed.

**Comment by DanielRuf** [comment]
Might be good to document this in the `contributing` section of the readme and a `CONTRIBUTING` file.

I will update the PR later today.

**Comment by DanielRuf** [comment]
I thinknwe just need `jest -- -u` or `npx jest -- -u`. Or `jest -u`?

**Comment by DanielRuf** [comment]
I think we just need `jest -- -u` or `npx jest -- -u`. Or `jest -u`?

**Pull request merged**
