### PR TITLE
 ref(icons): Update icons

### PR DESCRIPTION
**Pull request by priscilawebdev**
Converted Svg files into JSX Files +  Added the country names that we use in the translation files

### CODE REVIEW

**Comment by juanpicado** [comment]
Could you share why do you want to *Converted Svg files into JSX Files *?

**Comment by priscilawebdev** [comment]
@juanpicado I would like to have them as a component, having control over it

**Comment by DanielRuf** [comment]
I'm triggering all builds again. There seems to be some ntwork related issue with GHA. Please hang on.

**Comment by DanielRuf** [comment]
We should disable prettier for these files (generally I hate prettier).

Bildschirmfoto 2020-09-16 um 00 33 38

I guess after these errors are resolved the builds should be green.

**Review by DanielRuf — APPROVED** [review]
Awesome =)

LGTM

**Pull request merged**
