### PR TITLE
fix: correctly load font files - closes #128

### LINKED ISSUE #128: In the built app not found fonts
**Describe the bug**
in the built app not found fonts

**To Reproduce**
1. Clone repo
2. yarn install
3. yarn build
4. Replace folder `static` in `@verdaccio/ui-theme` or installing same as plugin (config `config.yaml` theme section)
5. http://localhost:4873/ 
6. DevTools (F12) -> Network

**Screenshots**
изображение

изображение

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

**Solution**
\tools\webpack.config.js  line 69
` - name: 'fonts/[name].[ext]',`
` + name: '/fonts/[name].[ext]',`

### PR DESCRIPTION
**Pull request by DanielRuf**
**Type:**
bug

**Description:**
This should fix the wrong paths for the Roboto fonts.

Resolves #128

### CODE REVIEW

**Comment by juanpicado** [comment]
@DanielRuf there is an issue https://app.circleci.com/jobs/github/verdaccio/ui/1551 could you check?

**Comment by DanielRuf** [comment]
I will have to check that in the react testing library repo as it seems they have an issue if is not explicitely loaded as css file (extension).

**Comment by DanielRuf** [comment]
See https://github.com/KyleAMathews/typefaces/issues/113

**Comment by juanpicado** [comment]
Thanks daniel !

**Pull request merged**
