### PR TITLE
feat: add browser features to browse by version

### PR DESCRIPTION
**Pull request by juanpicado**
**Type:** feat

**Description:**

Add version browsing capabilities per version

Screen Shot 2019-08-31 at 1 23 03 PM

Resolve: https://github.com/verdaccio/ui/issues/109

### CODE REVIEW

**Comment by kishok** [comment]
Hi juanpicado,
 
          Version Link not showing the corresponding link readMe , dependencies and tarball zip. please check this and provide fix asap.

**Comment by juanpicado** [comment]
Please explain you better, I don't know what you mean.

> please check this and provide fix asap. 

About this, please be nice, remember this is FOSS, **ASAP** word cannot be used on this project.

**Comment by kishok** [comment]
sorry i didn't mean anything to take it as serious but we are awaiting for this feature long before requested in this issue [#1079](https://github.com/verdaccio/verdaccio/issues/1079).i know this project is helpful for our local npm repository.i will change the way i mentioned earlier. 

thank you  
juanpicado

**Comment by juanpicado** [comment]
Hi @kishok about that feature, please check my comment here https://github.com/verdaccio/verdaccio/issues/1079#issuecomment-460083613
We don't store the README for all versions, for performance reasons, perhaps in the future we change that, but, this PR is just the beginning of it I guess.

Things move slow since we do this in our spare time, so patience is necessary for all of us. Things will come, soon or later.

**Pull request merged**
