### PR TITLE
fixing typography bug

### LINKED ISSUE #193: Wrong test on Registry Info
**Describe the bug**

Latest changes seems affected the Typography  of these fields

Screen Shot 2019-10-13 at 9 53 33 AM

Check here previous state: https://registry.verdaccio.org

### PR DESCRIPTION
**Pull request by jfamousket**
**Type:**
The following has been addressed in the PR:
fixing wrong test on registry info
**Description:**
Resolves #193

### CODE REVIEW

**Comment by juanpicado** [comment]
I think you need to update snapshots `yarn test -u`

**Comment by priscilawebdev** [comment]
@jfamousket Thank you much for your contribution 👏💪 unfortunately seems that another contributor have already fixed the issue in this PR: https://github.com/verdaccio/ui/pull/196

I doubled checked and it is fine..please see:

image

**Comment by priscilawebdev** [comment]
@jfamousket  I'm sorry, but since this issue has been resolved and it has been a while ... I am closing this issue 😉

**Comment by priscilawebdev** [comment]
@jfamousket I'm sorry, but since this issue has been resolved and it has been a while ... I am closing this issue 😉

**Pull request closed without merging**
