### PR TITLE
Remove capitalisation from greeting label

### PR DESCRIPTION
**Pull request by imjacobclark**
**Type:**

The following has been addressed in the PR:

Removing capitalisation from greeting label. When Verdaccio is welcoming a user based on their username, it is odd to capitalise the first letter, it is probably better to make zero assumptions about the formatting of the name rather than try and format it ourselves on the UI and simply accept whatever the auth source provides as a source of truth.

In the attached screenshot, you can see the strangeness I mention, "Imjacobclark" opposed to "imjacobclark".

Screenshot 2021-01-12 at 15 28 14

### CODE REVIEW

**Comment by chrisgrounds** [comment]
I actually like this feature. Can we have the option to choose whether we want capitalisation or not? Could you code that in as well @imjacobclark ?

**Comment by imjacobclark** [comment]
> I actually like this feature. Can we have the option to choose whether we want capitalisation or not? Could you code that in as well @imjacobclark ?

I think first would be to resolve for the simplest case and then potentially raise a ticket to customise in future.

**Review by priscilawebdev — APPROVED** [review]
I agree with you @imjacobclark Thanks for the PR 😉

**Comment by imjacobclark** [comment]
> I agree with you @imjacobclark Thanks for the PR 😉

Thanks @priscilawebdev! What's required to get this change merged? 

Thanks!

**Pull request merged**
