### PR TITLE
chore: changed the styling of the search bar

### PR DESCRIPTION
**Pull request by anikethsaha**
**Type:**
Chore+feature

The following has been addressed in the PR:

*  There is a related issue? NA
*  Unit or Functional tests are included in the PR: yes

**Description:**
Changed the styling of the searchbar to this 

image

With hover:

image

I made an addition to the `autocomplete` props, added a custom wrapper class name using emotion
styles.

### CODE REVIEW

**Comment by anikethsaha** [comment]
cc @juanpicado , what do you think about this change?

**Comment by juanpicado** [comment]
Current

Screen Shot 2019-10-26 at 8 45 36 PM

Proposal
Screen Shot 2019-10-26 at 8 45 41 PM

Frankly, I like the current one. It is more transparent to the user and do not looks like full of details. cc: @verdaccio/core-team

**Comment by priscilawebdev** [comment]
Sorry @anikethsaha but I agree with @juanpicado ..I prefer the current search style.

**Comment by anikethsaha** [comment]
No problem, My bad!!
I could have open an issue about this change rather than PR

**Pull request closed without merging**
