### PR TITLE
chore: add contributors

### PR DESCRIPTION
**Pull request by juanpicado**
**Type:** nice 

**Description:**

I want to add https://allcontributors.org/docs/en/cli/usage#all-contributors-check

result is this

https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTORS.md

and is being used like this

https://github.com/verdaccio/verdaccio/pull/1836#issuecomment-643580350

It can be on README.md or another file, on verdaccio core I decided a separate file because readme is quite long already.

### CODE REVIEW

**Review by kgrubb — APPROVED** [review]

**Comment by anikethsaha** [comment]
> **Type:** nice

:star:

**Review by anikethsaha — APPROVED** [review]

**Review by jamesgeorge007 — APPROVED** [review]

**Review by sergiohgz — APPROVED** [review]
Really good :ok_hand:

**Review by priscilawebdev — APPROVED** [review]
🚢🇮🇹 🤩

**Comment by juanpicado** [comment]
@all-contributors please add @tso1158687 for translation, code

**Comment by juanpicado** [comment]
@all-contributors please add @ayusharma  for maintenance, code

**Pull request merged**
