### PR TITLE
fix: formatDate

### PR DESCRIPTION
**Pull request by tmkn**
**Description:**
On Windows the tests failed for `formatDate`. It somehow took the timezone offset into account.
Adding the timezone offset before passing it to `date-fns/format` fixes it for Windows while remaining intact for Mac.

Since the tests now fully work on Windows we can add them to the CI pipeline?

### CODE REVIEW

**Comment by tmkn** [comment]
Also:
https://github.com/verdaccio/ui/blob/b2ea2e416740ff33f0cd6533bf970dc5a34ebc71/src/utils/package.ts#L42
is only used in unit tests. There are 5 tests for it but it's not used anywhere else.
If it doesn't serve a function it can be removed.

**Comment by juanpicado** [comment]
@tmkn good catch, Mmmmm .... if `formatDate` I would like to know when was removed ... if is really not need it, we should remove it

**Comment by tmkn** [comment]
@juanpicado `formatDate` is still used, `formatRepository` is only used in unit tests.

**Comment by juanpicado** [comment]
sorry the delay @tmkn I think I screw this PR :(

**Comment by tmkn** [comment]
@juanpicado no worry, should I remove `formatRepository` in the next PR? Did you take a look?

**Pull request merged**
